General:
  Header structure:
    first_header_prefix: null
    first_header_option: N/A
    first_header_postfix: null
    second_header_prefix: null
    second_header_option: Sub-Header
    second_header_postfix: null
