General:
  Header structure:
    first_header_prefix: n_
    first_header_option: Header
    first_header_postfix: '::'
    second_header_prefix: null
    second_header_option: Sub-Header
    second_header_postfix: null
